lang_list_names = {
    "English": ["en", "English"],
    "हिन्दी": ["hi", "Hindi"],
    "தமிழ்": ["ta", "Tamil"],
    "తెలుగు": ["te", "Telugu"],
    "ಕನ್ನಡ": ["kn", "Kannada"],
    "বাংলা": ["bn", "Bengali"],
    "संस्कृतम्": ["sa", "Sanskrit"],
    "മലയാളം": ["ml", "Malayalam"],
    "ગુજરાતી": ["gu", "Gujarati"],
    "मराठी": ["mr", "Marathi"],
    "اُردُو": ["ur", "Urdu"],
    "ਪੰਜਾਬੀ": ["pa", "Punjabi"],
    "ଓଡ଼ିଆ": ["or", "Odia"],
    "অসমীয়া": ["as", "Assamese"],
}
lang_list = dict(
    zip(lang_list_names.keys(), [lang_list_names[x][0] for x in lang_list_names])
)
script_list = {
    "हिन्दी": "Hindi",
    "বাংলা": "Bengali",
    "తెలుగు": "Telugu",
    "தமிழ்": "Tamil",
    "मराठी": "Marathi",
    "ગુજરાતી": "Gujarati",
    "മലയാളം": "Malayalam",
    "ಕನ್ನಡ": "Kannada",
    "ଓଡ଼ିଆ": "Odia",
    "कोंकणी": "Konkani",
    "অসমীয়া": "Assamese",
    "संस्कृतम्": "Sanskrit",
    "पूर्ण-देवनागरी": "Purna-Devanagari",
    "नेपाली": "Nepali",
    "कश्मीरी": "Kashmiri",
    "सिन्धी": "Sindhi",
    "සිංහල": "Sinhala",
    "ਪੰਜਾਬੀ": "Punjabi",
    "தமிழ்-Extended": "Tamil-Extended",
    "शारदा": "Sharada",
    "मोडी": "Modi",
    "सिद्धम्": "Siddham",
    "கிரந்த": "Granth",
    "ब्राह्मी": "Brahmi",
    "Romanized": "Romanized",
    "اُردُو": "Urdu",
}